# Generated by Django 3.1.4 on 2020-12-18 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    # 此程式依賴('article', '0001_initial')版本
    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pubDateTime']},
        ),  # 更改項目
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pubDateTime']},
        ),  # 更改項目
        migrations.AddField(
            model_name='article',
            name='pubDateTime',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),  # 增加欄位
        migrations.AddField(
            model_name='comment',
            name='pubDateTime',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),  # 增加欄位
    ]
